CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT);
CREATE TABLE IF NOT EXISTS "food_tracks" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT, "date" TEXT, "time" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL, "user_id" INTEGER NOT NULL CONSTRAINT "food_tracks_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "calories" TEXT, "protein" TEXT);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "email" TEXT NOT NULL COLLATE NOCASE, "hashed_password" TEXT NOT NULL, "confirmed_at" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE UNIQUE INDEX "users_email_index" ON "users" ("email");
CREATE TABLE IF NOT EXISTS "users_tokens" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "user_id" INTEGER NOT NULL CONSTRAINT "users_tokens_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "token" BLOB NOT NULL, "context" TEXT NOT NULL, "sent_to" TEXT, "inserted_at" TEXT NOT NULL);
CREATE INDEX "users_tokens_user_id_index" ON "users_tokens" ("user_id");
CREATE UNIQUE INDEX "users_tokens_context_token_index" ON "users_tokens" ("context", "token");
CREATE INDEX "food_tracks_user_id_index" ON "food_tracks" ("user_id");
INSERT INTO schema_migrations VALUES(20250415102110,'2025-04-19T12:25:15');
INSERT INTO schema_migrations VALUES(20250418094706,'2025-04-19T12:25:15');
INSERT INTO schema_migrations VALUES(20250419122328,'2025-04-19T12:25:15');
INSERT INTO schema_migrations VALUES(20250502212949,'2025-05-02T21:30:44');
