import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :food_tracker, FoodTrackerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: FoodTracker.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Set env value to :prod for production environment
config :food_tracker, env: :prod

# Configure Ollama API for production (Docker container name)
config :food_tracker, :ollama_api, base_url: "http://ollama:11434/api"

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
